# config/services.yaml
services:
    # Par défaut, les services sont autowirés, autoconfigurés et privés
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, subscribers, etc.
        public: false       # Les services sont privés par défaut

    # Rendre le HelloController accessible et injecter ses dépendances
    App\Controller\HelloController:
        tags: ['controller.service_arguments']

    # Rendre le HomeController accessible et injecter ses dépendances
    App\Controller\HomeController:
        tags: ['controller.service_arguments']

    App\Repository\ProductRepository:
        tags: ['controller.service_arguments']

    App\Repository\CategoryRepository:
        tags: ['controller.service_arguments']


    App\Controller\ProductController:
        tags: ['controller.service_arguments']

    App\Controller\CategoryController:
        tags: ['controller.service_arguments']

    App\Controller\CartController:
        tags: ['controller.service_arguments']

    App\Form\DataTransformer\CentimesTransformer:
        arguments: []



    # Si ce n'est pas déjà autowiré, on pourrait explicitement enregistrer le service Calculator (facultatif)
    App\Taxes\Calculator:
        arguments:
           $tva: 20

    Cocur\Slugify\Slugify: ~

    App\Taxes\Detector:
        arguments:
           $prixfix: 100

    # Fixtures
    App\DataFixtures\AppFixtures:
        tags: ['doctrine.fixture.orm']
        public: true

    # Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
    #     alias: Symfony\Component\PasswordHasher\Hasher\PasswordHasherInterface

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.password_hasher'

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Security\:
        resource: '../src/Security'

    App\Security\LoginFormAuthenticator:
        tags: ['controller.service_arguments']

    App\Stripe\StripeService:
        arguments:
           $secretKey: '%env(STRIPE_SECRET_KEY)%'
           $publicKey: '%env(STRIPE_PUBLIC_KEY)%'