# config/services.yaml
services:
    # Par défaut, les services sont autowirés, autoconfigurés et privés
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, subscribers, etc.
        public: false       # Les services sont privés par défaut

    # Rendre le HelloController accessible et injecter ses dépendances
    App\Controller\HelloController:
        tags: ['controller.service_arguments']

    # Si ce n'est pas déjà autowiré, on pourrait explicitement enregistrer le service Calculator (facultatif)
    App\Taxes\Calculator:
        arguments:
           $tva: 20

    Cocur\Slugify\Slugify: ~

    App\Taxes\Detector:
        arguments:
           $prixfix: 100
